/*
 * Access Analyzer
 * <p>Identity and Access Management Access Analyzer helps identify potential resource-access risks by enabling you to identify any policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview and validate public and cross-account access to your resources before deploying permissions changes. This guide describes the Identity and Access Management Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p> <p>To start using IAM Access Analyzer, you first need to create an analyzer.</p>
 *
 * The version of the OpenAPI document: 2019-11-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ConfigurationEbsSnapshot;
import org.openapitools.client.model.ConfigurationEcrRepository;
import org.openapitools.client.model.ConfigurationEfsFileSystem;
import org.openapitools.client.model.ConfigurationIamRole;
import org.openapitools.client.model.ConfigurationKmsKey;
import org.openapitools.client.model.ConfigurationRdsDbClusterSnapshot;
import org.openapitools.client.model.ConfigurationRdsDbSnapshot;
import org.openapitools.client.model.ConfigurationS3Bucket;
import org.openapitools.client.model.ConfigurationSecretsManagerSecret;
import org.openapitools.client.model.ConfigurationSnsTopic;
import org.openapitools.client.model.ConfigurationSqsQueue;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModelConfiguration
 */
public class ModelConfigurationTest {
    private final ModelConfiguration model = new ModelConfiguration();

    /**
     * Model tests for ModelConfiguration
     */
    @Test
    public void testModelConfiguration() {
        // TODO: test ModelConfiguration
    }

    /**
     * Test the property 'ebsSnapshot'
     */
    @Test
    public void ebsSnapshotTest() {
        // TODO: test ebsSnapshot
    }

    /**
     * Test the property 'ecrRepository'
     */
    @Test
    public void ecrRepositoryTest() {
        // TODO: test ecrRepository
    }

    /**
     * Test the property 'iamRole'
     */
    @Test
    public void iamRoleTest() {
        // TODO: test iamRole
    }

    /**
     * Test the property 'efsFileSystem'
     */
    @Test
    public void efsFileSystemTest() {
        // TODO: test efsFileSystem
    }

    /**
     * Test the property 'kmsKey'
     */
    @Test
    public void kmsKeyTest() {
        // TODO: test kmsKey
    }

    /**
     * Test the property 'rdsDbClusterSnapshot'
     */
    @Test
    public void rdsDbClusterSnapshotTest() {
        // TODO: test rdsDbClusterSnapshot
    }

    /**
     * Test the property 'rdsDbSnapshot'
     */
    @Test
    public void rdsDbSnapshotTest() {
        // TODO: test rdsDbSnapshot
    }

    /**
     * Test the property 'secretsManagerSecret'
     */
    @Test
    public void secretsManagerSecretTest() {
        // TODO: test secretsManagerSecret
    }

    /**
     * Test the property 's3Bucket'
     */
    @Test
    public void s3BucketTest() {
        // TODO: test s3Bucket
    }

    /**
     * Test the property 'snsTopic'
     */
    @Test
    public void snsTopicTest() {
        // TODO: test snsTopic
    }

    /**
     * Test the property 'sqsQueue'
     */
    @Test
    public void sqsQueueTest() {
        // TODO: test sqsQueue
    }

}
