/*
 * Access Analyzer
 * <p>Identity and Access Management Access Analyzer helps identify potential resource-access risks by enabling you to identify any policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview and validate public and cross-account access to your resources before deploying permissions changes. This guide describes the Identity and Access Management Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p> <p>To start using IAM Access Analyzer, you first need to create an analyzer.</p>
 *
 * The version of the OpenAPI document: 2019-11-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * FindingSourceDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:05.234024+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class FindingSourceDetail {
  public static final String SERIALIZED_NAME_ACCESS_POINT_ARN = "accessPointArn";
  @SerializedName(SERIALIZED_NAME_ACCESS_POINT_ARN)
  @javax.annotation.Nullable
  private String accessPointArn;

  public static final String SERIALIZED_NAME_ACCESS_POINT_ACCOUNT = "accessPointAccount";
  @SerializedName(SERIALIZED_NAME_ACCESS_POINT_ACCOUNT)
  @javax.annotation.Nullable
  private String accessPointAccount;

  public FindingSourceDetail() {
  }

  public FindingSourceDetail accessPointArn(@javax.annotation.Nullable String accessPointArn) {
    this.accessPointArn = accessPointArn;
    return this;
  }

  /**
   * Get accessPointArn
   * @return accessPointArn
   */
  @javax.annotation.Nullable
  public String getAccessPointArn() {
    return accessPointArn;
  }

  public void setAccessPointArn(@javax.annotation.Nullable String accessPointArn) {
    this.accessPointArn = accessPointArn;
  }


  public FindingSourceDetail accessPointAccount(@javax.annotation.Nullable String accessPointAccount) {
    this.accessPointAccount = accessPointAccount;
    return this;
  }

  /**
   * Get accessPointAccount
   * @return accessPointAccount
   */
  @javax.annotation.Nullable
  public String getAccessPointAccount() {
    return accessPointAccount;
  }

  public void setAccessPointAccount(@javax.annotation.Nullable String accessPointAccount) {
    this.accessPointAccount = accessPointAccount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FindingSourceDetail findingSourceDetail = (FindingSourceDetail) o;
    return Objects.equals(this.accessPointArn, findingSourceDetail.accessPointArn) &&
        Objects.equals(this.accessPointAccount, findingSourceDetail.accessPointAccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessPointArn, accessPointAccount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FindingSourceDetail {\n");
    sb.append("    accessPointArn: ").append(toIndentedString(accessPointArn)).append("\n");
    sb.append("    accessPointAccount: ").append(toIndentedString(accessPointAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accessPointArn");
    openapiFields.add("accessPointAccount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FindingSourceDetail
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FindingSourceDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FindingSourceDetail is not found in the empty JSON string", FindingSourceDetail.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FindingSourceDetail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FindingSourceDetail` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `accessPointArn`
      if (jsonObj.get("accessPointArn") != null && !jsonObj.get("accessPointArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("accessPointArn"));
      }
      // validate the optional field `accessPointAccount`
      if (jsonObj.get("accessPointAccount") != null && !jsonObj.get("accessPointAccount").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("accessPointAccount"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FindingSourceDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FindingSourceDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FindingSourceDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FindingSourceDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<FindingSourceDetail>() {
           @Override
           public void write(JsonWriter out, FindingSourceDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FindingSourceDetail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FindingSourceDetail given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FindingSourceDetail
   * @throws IOException if the JSON string is invalid with respect to FindingSourceDetail
   */
  public static FindingSourceDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FindingSourceDetail.class);
  }

  /**
   * Convert an instance of FindingSourceDetail to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

