/*
 * Access Analyzer
 * <p>Identity and Access Management Access Analyzer helps identify potential resource-access risks by enabling you to identify any policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview and validate public and cross-account access to your resources before deploying permissions changes. This guide describes the Identity and Access Management Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p> <p>To start using IAM Access Analyzer, you first need to create an analyzer.</p>
 *
 * The version of the OpenAPI document: 2019-11-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GeneratedPolicyPropertiesCloudTrailProperties;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Contains the generated policy details.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:05.234024+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GeneratedPolicyProperties {
  public static final String SERIALIZED_NAME_IS_COMPLETE = "isComplete";
  @SerializedName(SERIALIZED_NAME_IS_COMPLETE)
  @javax.annotation.Nullable
  private Boolean isComplete;

  public static final String SERIALIZED_NAME_PRINCIPAL_ARN = "principalArn";
  @SerializedName(SERIALIZED_NAME_PRINCIPAL_ARN)
  @javax.annotation.Nonnull
  private String principalArn;

  public static final String SERIALIZED_NAME_CLOUD_TRAIL_PROPERTIES = "cloudTrailProperties";
  @SerializedName(SERIALIZED_NAME_CLOUD_TRAIL_PROPERTIES)
  @javax.annotation.Nullable
  private GeneratedPolicyPropertiesCloudTrailProperties cloudTrailProperties;

  public GeneratedPolicyProperties() {
  }

  public GeneratedPolicyProperties isComplete(@javax.annotation.Nullable Boolean isComplete) {
    this.isComplete = isComplete;
    return this;
  }

  /**
   * Get isComplete
   * @return isComplete
   */
  @javax.annotation.Nullable
  public Boolean getIsComplete() {
    return isComplete;
  }

  public void setIsComplete(@javax.annotation.Nullable Boolean isComplete) {
    this.isComplete = isComplete;
  }


  public GeneratedPolicyProperties principalArn(@javax.annotation.Nonnull String principalArn) {
    this.principalArn = principalArn;
    return this;
  }

  /**
   * Get principalArn
   * @return principalArn
   */
  @javax.annotation.Nonnull
  public String getPrincipalArn() {
    return principalArn;
  }

  public void setPrincipalArn(@javax.annotation.Nonnull String principalArn) {
    this.principalArn = principalArn;
  }


  public GeneratedPolicyProperties cloudTrailProperties(@javax.annotation.Nullable GeneratedPolicyPropertiesCloudTrailProperties cloudTrailProperties) {
    this.cloudTrailProperties = cloudTrailProperties;
    return this;
  }

  /**
   * Get cloudTrailProperties
   * @return cloudTrailProperties
   */
  @javax.annotation.Nullable
  public GeneratedPolicyPropertiesCloudTrailProperties getCloudTrailProperties() {
    return cloudTrailProperties;
  }

  public void setCloudTrailProperties(@javax.annotation.Nullable GeneratedPolicyPropertiesCloudTrailProperties cloudTrailProperties) {
    this.cloudTrailProperties = cloudTrailProperties;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneratedPolicyProperties generatedPolicyProperties = (GeneratedPolicyProperties) o;
    return Objects.equals(this.isComplete, generatedPolicyProperties.isComplete) &&
        Objects.equals(this.principalArn, generatedPolicyProperties.principalArn) &&
        Objects.equals(this.cloudTrailProperties, generatedPolicyProperties.cloudTrailProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isComplete, principalArn, cloudTrailProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneratedPolicyProperties {\n");
    sb.append("    isComplete: ").append(toIndentedString(isComplete)).append("\n");
    sb.append("    principalArn: ").append(toIndentedString(principalArn)).append("\n");
    sb.append("    cloudTrailProperties: ").append(toIndentedString(cloudTrailProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isComplete");
    openapiFields.add("principalArn");
    openapiFields.add("cloudTrailProperties");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("principalArn");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GeneratedPolicyProperties
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GeneratedPolicyProperties.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GeneratedPolicyProperties is not found in the empty JSON string", GeneratedPolicyProperties.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GeneratedPolicyProperties.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GeneratedPolicyProperties` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GeneratedPolicyProperties.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `isComplete`
      if (jsonObj.get("isComplete") != null && !jsonObj.get("isComplete").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isComplete"));
      }
      // validate the required field `principalArn`
      String.validateJsonElement(jsonObj.get("principalArn"));
      // validate the optional field `cloudTrailProperties`
      if (jsonObj.get("cloudTrailProperties") != null && !jsonObj.get("cloudTrailProperties").isJsonNull()) {
        GeneratedPolicyPropertiesCloudTrailProperties.validateJsonElement(jsonObj.get("cloudTrailProperties"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GeneratedPolicyProperties.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GeneratedPolicyProperties' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GeneratedPolicyProperties> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GeneratedPolicyProperties.class));

       return (TypeAdapter<T>) new TypeAdapter<GeneratedPolicyProperties>() {
           @Override
           public void write(JsonWriter out, GeneratedPolicyProperties value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GeneratedPolicyProperties read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GeneratedPolicyProperties given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GeneratedPolicyProperties
   * @throws IOException if the JSON string is invalid with respect to GeneratedPolicyProperties
   */
  public static GeneratedPolicyProperties fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GeneratedPolicyProperties.class);
  }

  /**
   * Convert an instance of GeneratedPolicyProperties to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

