/*
 * Access Analyzer
 * <p>Identity and Access Management Access Analyzer helps identify potential resource-access risks by enabling you to identify any policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview and validate public and cross-account access to your resources before deploying permissions changes. This guide describes the Identity and Access Management Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p> <p>To start using IAM Access Analyzer, you first need to create an analyzer.</p>
 *
 * The version of the OpenAPI document: 2019-11-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.FindingStatus;
import org.openapitools.client.model.ResourceType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetFindingResponseFinding
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:05.234024+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GetFindingResponseFinding {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_PRINCIPAL = "principal";
  @SerializedName(SERIALIZED_NAME_PRINCIPAL)
  @javax.annotation.Nullable
  private Map principal;

  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  @javax.annotation.Nullable
  private List action;

  public static final String SERIALIZED_NAME_RESOURCE = "resource";
  @SerializedName(SERIALIZED_NAME_RESOURCE)
  @javax.annotation.Nullable
  private String resource;

  public static final String SERIALIZED_NAME_IS_PUBLIC = "isPublic";
  @SerializedName(SERIALIZED_NAME_IS_PUBLIC)
  @javax.annotation.Nullable
  private Boolean isPublic;

  public static final String SERIALIZED_NAME_RESOURCE_TYPE = "resourceType";
  @SerializedName(SERIALIZED_NAME_RESOURCE_TYPE)
  @javax.annotation.Nonnull
  private ResourceType resourceType;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  @javax.annotation.Nonnull
  private Map condition;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_ANALYZED_AT = "analyzedAt";
  @SerializedName(SERIALIZED_NAME_ANALYZED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime analyzedAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private FindingStatus status;

  public static final String SERIALIZED_NAME_RESOURCE_OWNER_ACCOUNT = "resourceOwnerAccount";
  @SerializedName(SERIALIZED_NAME_RESOURCE_OWNER_ACCOUNT)
  @javax.annotation.Nonnull
  private String resourceOwnerAccount;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @javax.annotation.Nullable
  private String error;

  public static final String SERIALIZED_NAME_SOURCES = "sources";
  @SerializedName(SERIALIZED_NAME_SOURCES)
  @javax.annotation.Nullable
  private List sources;

  public GetFindingResponseFinding() {
  }

  public GetFindingResponseFinding id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public GetFindingResponseFinding principal(@javax.annotation.Nullable Map principal) {
    this.principal = principal;
    return this;
  }

  /**
   * Get principal
   * @return principal
   */
  @javax.annotation.Nullable
  public Map getPrincipal() {
    return principal;
  }

  public void setPrincipal(@javax.annotation.Nullable Map principal) {
    this.principal = principal;
  }


  public GetFindingResponseFinding action(@javax.annotation.Nullable List action) {
    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @javax.annotation.Nullable
  public List getAction() {
    return action;
  }

  public void setAction(@javax.annotation.Nullable List action) {
    this.action = action;
  }


  public GetFindingResponseFinding resource(@javax.annotation.Nullable String resource) {
    this.resource = resource;
    return this;
  }

  /**
   * Get resource
   * @return resource
   */
  @javax.annotation.Nullable
  public String getResource() {
    return resource;
  }

  public void setResource(@javax.annotation.Nullable String resource) {
    this.resource = resource;
  }


  public GetFindingResponseFinding isPublic(@javax.annotation.Nullable Boolean isPublic) {
    this.isPublic = isPublic;
    return this;
  }

  /**
   * Get isPublic
   * @return isPublic
   */
  @javax.annotation.Nullable
  public Boolean getIsPublic() {
    return isPublic;
  }

  public void setIsPublic(@javax.annotation.Nullable Boolean isPublic) {
    this.isPublic = isPublic;
  }


  public GetFindingResponseFinding resourceType(@javax.annotation.Nonnull ResourceType resourceType) {
    this.resourceType = resourceType;
    return this;
  }

  /**
   * Get resourceType
   * @return resourceType
   */
  @javax.annotation.Nonnull
  public ResourceType getResourceType() {
    return resourceType;
  }

  public void setResourceType(@javax.annotation.Nonnull ResourceType resourceType) {
    this.resourceType = resourceType;
  }


  public GetFindingResponseFinding condition(@javax.annotation.Nonnull Map condition) {
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   */
  @javax.annotation.Nonnull
  public Map getCondition() {
    return condition;
  }

  public void setCondition(@javax.annotation.Nonnull Map condition) {
    this.condition = condition;
  }


  public GetFindingResponseFinding createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public GetFindingResponseFinding analyzedAt(@javax.annotation.Nonnull OffsetDateTime analyzedAt) {
    this.analyzedAt = analyzedAt;
    return this;
  }

  /**
   * Get analyzedAt
   * @return analyzedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getAnalyzedAt() {
    return analyzedAt;
  }

  public void setAnalyzedAt(@javax.annotation.Nonnull OffsetDateTime analyzedAt) {
    this.analyzedAt = analyzedAt;
  }


  public GetFindingResponseFinding updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public GetFindingResponseFinding status(@javax.annotation.Nonnull FindingStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public FindingStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull FindingStatus status) {
    this.status = status;
  }


  public GetFindingResponseFinding resourceOwnerAccount(@javax.annotation.Nonnull String resourceOwnerAccount) {
    this.resourceOwnerAccount = resourceOwnerAccount;
    return this;
  }

  /**
   * Get resourceOwnerAccount
   * @return resourceOwnerAccount
   */
  @javax.annotation.Nonnull
  public String getResourceOwnerAccount() {
    return resourceOwnerAccount;
  }

  public void setResourceOwnerAccount(@javax.annotation.Nonnull String resourceOwnerAccount) {
    this.resourceOwnerAccount = resourceOwnerAccount;
  }


  public GetFindingResponseFinding error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  public GetFindingResponseFinding sources(@javax.annotation.Nullable List sources) {
    this.sources = sources;
    return this;
  }

  /**
   * Get sources
   * @return sources
   */
  @javax.annotation.Nullable
  public List getSources() {
    return sources;
  }

  public void setSources(@javax.annotation.Nullable List sources) {
    this.sources = sources;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFindingResponseFinding getFindingResponseFinding = (GetFindingResponseFinding) o;
    return Objects.equals(this.id, getFindingResponseFinding.id) &&
        Objects.equals(this.principal, getFindingResponseFinding.principal) &&
        Objects.equals(this.action, getFindingResponseFinding.action) &&
        Objects.equals(this.resource, getFindingResponseFinding.resource) &&
        Objects.equals(this.isPublic, getFindingResponseFinding.isPublic) &&
        Objects.equals(this.resourceType, getFindingResponseFinding.resourceType) &&
        Objects.equals(this.condition, getFindingResponseFinding.condition) &&
        Objects.equals(this.createdAt, getFindingResponseFinding.createdAt) &&
        Objects.equals(this.analyzedAt, getFindingResponseFinding.analyzedAt) &&
        Objects.equals(this.updatedAt, getFindingResponseFinding.updatedAt) &&
        Objects.equals(this.status, getFindingResponseFinding.status) &&
        Objects.equals(this.resourceOwnerAccount, getFindingResponseFinding.resourceOwnerAccount) &&
        Objects.equals(this.error, getFindingResponseFinding.error) &&
        Objects.equals(this.sources, getFindingResponseFinding.sources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, principal, action, resource, isPublic, resourceType, condition, createdAt, analyzedAt, updatedAt, status, resourceOwnerAccount, error, sources);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFindingResponseFinding {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    principal: ").append(toIndentedString(principal)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    analyzedAt: ").append(toIndentedString(analyzedAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    resourceOwnerAccount: ").append(toIndentedString(resourceOwnerAccount)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("principal");
    openapiFields.add("action");
    openapiFields.add("resource");
    openapiFields.add("isPublic");
    openapiFields.add("resourceType");
    openapiFields.add("condition");
    openapiFields.add("createdAt");
    openapiFields.add("analyzedAt");
    openapiFields.add("updatedAt");
    openapiFields.add("status");
    openapiFields.add("resourceOwnerAccount");
    openapiFields.add("error");
    openapiFields.add("sources");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("resourceType");
    openapiRequiredFields.add("condition");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("analyzedAt");
    openapiRequiredFields.add("updatedAt");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("resourceOwnerAccount");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetFindingResponseFinding
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetFindingResponseFinding.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetFindingResponseFinding is not found in the empty JSON string", GetFindingResponseFinding.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetFindingResponseFinding.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetFindingResponseFinding` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetFindingResponseFinding.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `id`
      String.validateJsonElement(jsonObj.get("id"));
      // validate the optional field `principal`
      if (jsonObj.get("principal") != null && !jsonObj.get("principal").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("principal"));
      }
      // validate the optional field `action`
      if (jsonObj.get("action") != null && !jsonObj.get("action").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("action"));
      }
      // validate the optional field `resource`
      if (jsonObj.get("resource") != null && !jsonObj.get("resource").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("resource"));
      }
      // validate the optional field `isPublic`
      if (jsonObj.get("isPublic") != null && !jsonObj.get("isPublic").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isPublic"));
      }
      // validate the required field `resourceType`
      ResourceType.validateJsonElement(jsonObj.get("resourceType"));
      // validate the required field `condition`
      Map.validateJsonElement(jsonObj.get("condition"));
      // validate the required field `createdAt`
      OffsetDateTime.validateJsonElement(jsonObj.get("createdAt"));
      // validate the required field `analyzedAt`
      OffsetDateTime.validateJsonElement(jsonObj.get("analyzedAt"));
      // validate the required field `updatedAt`
      OffsetDateTime.validateJsonElement(jsonObj.get("updatedAt"));
      // validate the required field `status`
      FindingStatus.validateJsonElement(jsonObj.get("status"));
      // validate the required field `resourceOwnerAccount`
      String.validateJsonElement(jsonObj.get("resourceOwnerAccount"));
      // validate the optional field `error`
      if (jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("error"));
      }
      // validate the optional field `sources`
      if (jsonObj.get("sources") != null && !jsonObj.get("sources").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("sources"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetFindingResponseFinding.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetFindingResponseFinding' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetFindingResponseFinding> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetFindingResponseFinding.class));

       return (TypeAdapter<T>) new TypeAdapter<GetFindingResponseFinding>() {
           @Override
           public void write(JsonWriter out, GetFindingResponseFinding value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetFindingResponseFinding read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetFindingResponseFinding given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetFindingResponseFinding
   * @throws IOException if the JSON string is invalid with respect to GetFindingResponseFinding
   */
  public static GetFindingResponseFinding fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetFindingResponseFinding.class);
  }

  /**
   * Convert an instance of GetFindingResponseFinding to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

