/*
 * Access Analyzer
 * <p>Identity and Access Management Access Analyzer helps identify potential resource-access risks by enabling you to identify any policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview and validate public and cross-account access to your resources before deploying permissions changes. This guide describes the Identity and Access Management Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p> <p>To start using IAM Access Analyzer, you first need to create an analyzer.</p>
 *
 * The version of the OpenAPI document: 2019-11-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.KmsGrantConfigurationConstraints;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A proposed grant configuration for a KMS key. For more information, see &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/kms/latest/APIReference/API_CreateGrant.html\&quot;&gt;CreateGrant&lt;/a&gt;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:05.234024+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class KmsGrantConfiguration {
  public static final String SERIALIZED_NAME_OPERATIONS = "operations";
  @SerializedName(SERIALIZED_NAME_OPERATIONS)
  @javax.annotation.Nonnull
  private List operations;

  public static final String SERIALIZED_NAME_GRANTEE_PRINCIPAL = "granteePrincipal";
  @SerializedName(SERIALIZED_NAME_GRANTEE_PRINCIPAL)
  @javax.annotation.Nonnull
  private String granteePrincipal;

  public static final String SERIALIZED_NAME_RETIRING_PRINCIPAL = "retiringPrincipal";
  @SerializedName(SERIALIZED_NAME_RETIRING_PRINCIPAL)
  @javax.annotation.Nullable
  private String retiringPrincipal;

  public static final String SERIALIZED_NAME_CONSTRAINTS = "constraints";
  @SerializedName(SERIALIZED_NAME_CONSTRAINTS)
  @javax.annotation.Nullable
  private KmsGrantConfigurationConstraints constraints;

  public static final String SERIALIZED_NAME_ISSUING_ACCOUNT = "issuingAccount";
  @SerializedName(SERIALIZED_NAME_ISSUING_ACCOUNT)
  @javax.annotation.Nonnull
  private String issuingAccount;

  public KmsGrantConfiguration() {
  }

  public KmsGrantConfiguration operations(@javax.annotation.Nonnull List operations) {
    this.operations = operations;
    return this;
  }

  /**
   * Get operations
   * @return operations
   */
  @javax.annotation.Nonnull
  public List getOperations() {
    return operations;
  }

  public void setOperations(@javax.annotation.Nonnull List operations) {
    this.operations = operations;
  }


  public KmsGrantConfiguration granteePrincipal(@javax.annotation.Nonnull String granteePrincipal) {
    this.granteePrincipal = granteePrincipal;
    return this;
  }

  /**
   * Get granteePrincipal
   * @return granteePrincipal
   */
  @javax.annotation.Nonnull
  public String getGranteePrincipal() {
    return granteePrincipal;
  }

  public void setGranteePrincipal(@javax.annotation.Nonnull String granteePrincipal) {
    this.granteePrincipal = granteePrincipal;
  }


  public KmsGrantConfiguration retiringPrincipal(@javax.annotation.Nullable String retiringPrincipal) {
    this.retiringPrincipal = retiringPrincipal;
    return this;
  }

  /**
   * Get retiringPrincipal
   * @return retiringPrincipal
   */
  @javax.annotation.Nullable
  public String getRetiringPrincipal() {
    return retiringPrincipal;
  }

  public void setRetiringPrincipal(@javax.annotation.Nullable String retiringPrincipal) {
    this.retiringPrincipal = retiringPrincipal;
  }


  public KmsGrantConfiguration constraints(@javax.annotation.Nullable KmsGrantConfigurationConstraints constraints) {
    this.constraints = constraints;
    return this;
  }

  /**
   * Get constraints
   * @return constraints
   */
  @javax.annotation.Nullable
  public KmsGrantConfigurationConstraints getConstraints() {
    return constraints;
  }

  public void setConstraints(@javax.annotation.Nullable KmsGrantConfigurationConstraints constraints) {
    this.constraints = constraints;
  }


  public KmsGrantConfiguration issuingAccount(@javax.annotation.Nonnull String issuingAccount) {
    this.issuingAccount = issuingAccount;
    return this;
  }

  /**
   * Get issuingAccount
   * @return issuingAccount
   */
  @javax.annotation.Nonnull
  public String getIssuingAccount() {
    return issuingAccount;
  }

  public void setIssuingAccount(@javax.annotation.Nonnull String issuingAccount) {
    this.issuingAccount = issuingAccount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KmsGrantConfiguration kmsGrantConfiguration = (KmsGrantConfiguration) o;
    return Objects.equals(this.operations, kmsGrantConfiguration.operations) &&
        Objects.equals(this.granteePrincipal, kmsGrantConfiguration.granteePrincipal) &&
        Objects.equals(this.retiringPrincipal, kmsGrantConfiguration.retiringPrincipal) &&
        Objects.equals(this.constraints, kmsGrantConfiguration.constraints) &&
        Objects.equals(this.issuingAccount, kmsGrantConfiguration.issuingAccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operations, granteePrincipal, retiringPrincipal, constraints, issuingAccount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KmsGrantConfiguration {\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    granteePrincipal: ").append(toIndentedString(granteePrincipal)).append("\n");
    sb.append("    retiringPrincipal: ").append(toIndentedString(retiringPrincipal)).append("\n");
    sb.append("    constraints: ").append(toIndentedString(constraints)).append("\n");
    sb.append("    issuingAccount: ").append(toIndentedString(issuingAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("operations");
    openapiFields.add("granteePrincipal");
    openapiFields.add("retiringPrincipal");
    openapiFields.add("constraints");
    openapiFields.add("issuingAccount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("operations");
    openapiRequiredFields.add("granteePrincipal");
    openapiRequiredFields.add("issuingAccount");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to KmsGrantConfiguration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!KmsGrantConfiguration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in KmsGrantConfiguration is not found in the empty JSON string", KmsGrantConfiguration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!KmsGrantConfiguration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `KmsGrantConfiguration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : KmsGrantConfiguration.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `operations`
      List.validateJsonElement(jsonObj.get("operations"));
      // validate the required field `granteePrincipal`
      String.validateJsonElement(jsonObj.get("granteePrincipal"));
      // validate the optional field `retiringPrincipal`
      if (jsonObj.get("retiringPrincipal") != null && !jsonObj.get("retiringPrincipal").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("retiringPrincipal"));
      }
      // validate the optional field `constraints`
      if (jsonObj.get("constraints") != null && !jsonObj.get("constraints").isJsonNull()) {
        KmsGrantConfigurationConstraints.validateJsonElement(jsonObj.get("constraints"));
      }
      // validate the required field `issuingAccount`
      String.validateJsonElement(jsonObj.get("issuingAccount"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!KmsGrantConfiguration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'KmsGrantConfiguration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<KmsGrantConfiguration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(KmsGrantConfiguration.class));

       return (TypeAdapter<T>) new TypeAdapter<KmsGrantConfiguration>() {
           @Override
           public void write(JsonWriter out, KmsGrantConfiguration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public KmsGrantConfiguration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of KmsGrantConfiguration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of KmsGrantConfiguration
   * @throws IOException if the JSON string is invalid with respect to KmsGrantConfiguration
   */
  public static KmsGrantConfiguration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, KmsGrantConfiguration.class);
  }

  /**
   * Convert an instance of KmsGrantConfiguration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

