/*
 * Access Analyzer
 * <p>Identity and Access Management Access Analyzer helps identify potential resource-access risks by enabling you to identify any policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview and validate public and cross-account access to your resources before deploying permissions changes. This guide describes the Identity and Access Management Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p> <p>To start using IAM Access Analyzer, you first need to create an analyzer.</p>
 *
 * The version of the OpenAPI document: 2019-11-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * S3AccessPointConfigurationPublicAccessBlock
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:05.234024+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class S3AccessPointConfigurationPublicAccessBlock {
  public static final String SERIALIZED_NAME_IGNORE_PUBLIC_ACLS = "ignorePublicAcls";
  @SerializedName(SERIALIZED_NAME_IGNORE_PUBLIC_ACLS)
  @javax.annotation.Nonnull
  private Boolean ignorePublicAcls;

  public static final String SERIALIZED_NAME_RESTRICT_PUBLIC_BUCKETS = "restrictPublicBuckets";
  @SerializedName(SERIALIZED_NAME_RESTRICT_PUBLIC_BUCKETS)
  @javax.annotation.Nonnull
  private Boolean restrictPublicBuckets;

  public S3AccessPointConfigurationPublicAccessBlock() {
  }

  public S3AccessPointConfigurationPublicAccessBlock ignorePublicAcls(@javax.annotation.Nonnull Boolean ignorePublicAcls) {
    this.ignorePublicAcls = ignorePublicAcls;
    return this;
  }

  /**
   * Get ignorePublicAcls
   * @return ignorePublicAcls
   */
  @javax.annotation.Nonnull
  public Boolean getIgnorePublicAcls() {
    return ignorePublicAcls;
  }

  public void setIgnorePublicAcls(@javax.annotation.Nonnull Boolean ignorePublicAcls) {
    this.ignorePublicAcls = ignorePublicAcls;
  }


  public S3AccessPointConfigurationPublicAccessBlock restrictPublicBuckets(@javax.annotation.Nonnull Boolean restrictPublicBuckets) {
    this.restrictPublicBuckets = restrictPublicBuckets;
    return this;
  }

  /**
   * Get restrictPublicBuckets
   * @return restrictPublicBuckets
   */
  @javax.annotation.Nonnull
  public Boolean getRestrictPublicBuckets() {
    return restrictPublicBuckets;
  }

  public void setRestrictPublicBuckets(@javax.annotation.Nonnull Boolean restrictPublicBuckets) {
    this.restrictPublicBuckets = restrictPublicBuckets;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S3AccessPointConfigurationPublicAccessBlock s3AccessPointConfigurationPublicAccessBlock = (S3AccessPointConfigurationPublicAccessBlock) o;
    return Objects.equals(this.ignorePublicAcls, s3AccessPointConfigurationPublicAccessBlock.ignorePublicAcls) &&
        Objects.equals(this.restrictPublicBuckets, s3AccessPointConfigurationPublicAccessBlock.restrictPublicBuckets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ignorePublicAcls, restrictPublicBuckets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S3AccessPointConfigurationPublicAccessBlock {\n");
    sb.append("    ignorePublicAcls: ").append(toIndentedString(ignorePublicAcls)).append("\n");
    sb.append("    restrictPublicBuckets: ").append(toIndentedString(restrictPublicBuckets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ignorePublicAcls");
    openapiFields.add("restrictPublicBuckets");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ignorePublicAcls");
    openapiRequiredFields.add("restrictPublicBuckets");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to S3AccessPointConfigurationPublicAccessBlock
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!S3AccessPointConfigurationPublicAccessBlock.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in S3AccessPointConfigurationPublicAccessBlock is not found in the empty JSON string", S3AccessPointConfigurationPublicAccessBlock.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!S3AccessPointConfigurationPublicAccessBlock.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `S3AccessPointConfigurationPublicAccessBlock` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : S3AccessPointConfigurationPublicAccessBlock.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `ignorePublicAcls`
      Boolean.validateJsonElement(jsonObj.get("ignorePublicAcls"));
      // validate the required field `restrictPublicBuckets`
      Boolean.validateJsonElement(jsonObj.get("restrictPublicBuckets"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!S3AccessPointConfigurationPublicAccessBlock.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'S3AccessPointConfigurationPublicAccessBlock' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<S3AccessPointConfigurationPublicAccessBlock> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(S3AccessPointConfigurationPublicAccessBlock.class));

       return (TypeAdapter<T>) new TypeAdapter<S3AccessPointConfigurationPublicAccessBlock>() {
           @Override
           public void write(JsonWriter out, S3AccessPointConfigurationPublicAccessBlock value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public S3AccessPointConfigurationPublicAccessBlock read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of S3AccessPointConfigurationPublicAccessBlock given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of S3AccessPointConfigurationPublicAccessBlock
   * @throws IOException if the JSON string is invalid with respect to S3AccessPointConfigurationPublicAccessBlock
   */
  public static S3AccessPointConfigurationPublicAccessBlock fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, S3AccessPointConfigurationPublicAccessBlock.class);
  }

  /**
   * Convert an instance of S3AccessPointConfigurationPublicAccessBlock to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

