/*
 * Access Analyzer
 * <p>Identity and Access Management Access Analyzer helps identify potential resource-access risks by enabling you to identify any policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview and validate public and cross-account access to your resources before deploying permissions changes. This guide describes the Identity and Access Management Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p> <p>To start using IAM Access Analyzer, you first need to create an analyzer.</p>
 *
 * The version of the OpenAPI document: 2019-11-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AclPermission;
import org.openapitools.client.model.S3BucketAclGrantConfigurationGrantee;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A proposed access control list grant configuration for an Amazon S3 bucket. For more information, see &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#setting-acls\&quot;&gt;How to Specify an ACL&lt;/a&gt;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:05.234024+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class S3BucketAclGrantConfiguration {
  public static final String SERIALIZED_NAME_PERMISSION = "permission";
  @SerializedName(SERIALIZED_NAME_PERMISSION)
  @javax.annotation.Nonnull
  private AclPermission permission;

  public static final String SERIALIZED_NAME_GRANTEE = "grantee";
  @SerializedName(SERIALIZED_NAME_GRANTEE)
  @javax.annotation.Nonnull
  private S3BucketAclGrantConfigurationGrantee grantee;

  public S3BucketAclGrantConfiguration() {
  }

  public S3BucketAclGrantConfiguration permission(@javax.annotation.Nonnull AclPermission permission) {
    this.permission = permission;
    return this;
  }

  /**
   * Get permission
   * @return permission
   */
  @javax.annotation.Nonnull
  public AclPermission getPermission() {
    return permission;
  }

  public void setPermission(@javax.annotation.Nonnull AclPermission permission) {
    this.permission = permission;
  }


  public S3BucketAclGrantConfiguration grantee(@javax.annotation.Nonnull S3BucketAclGrantConfigurationGrantee grantee) {
    this.grantee = grantee;
    return this;
  }

  /**
   * Get grantee
   * @return grantee
   */
  @javax.annotation.Nonnull
  public S3BucketAclGrantConfigurationGrantee getGrantee() {
    return grantee;
  }

  public void setGrantee(@javax.annotation.Nonnull S3BucketAclGrantConfigurationGrantee grantee) {
    this.grantee = grantee;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S3BucketAclGrantConfiguration s3BucketAclGrantConfiguration = (S3BucketAclGrantConfiguration) o;
    return Objects.equals(this.permission, s3BucketAclGrantConfiguration.permission) &&
        Objects.equals(this.grantee, s3BucketAclGrantConfiguration.grantee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permission, grantee);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S3BucketAclGrantConfiguration {\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("    grantee: ").append(toIndentedString(grantee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("permission");
    openapiFields.add("grantee");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("permission");
    openapiRequiredFields.add("grantee");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to S3BucketAclGrantConfiguration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!S3BucketAclGrantConfiguration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in S3BucketAclGrantConfiguration is not found in the empty JSON string", S3BucketAclGrantConfiguration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!S3BucketAclGrantConfiguration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `S3BucketAclGrantConfiguration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : S3BucketAclGrantConfiguration.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `permission`
      AclPermission.validateJsonElement(jsonObj.get("permission"));
      // validate the required field `grantee`
      S3BucketAclGrantConfigurationGrantee.validateJsonElement(jsonObj.get("grantee"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!S3BucketAclGrantConfiguration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'S3BucketAclGrantConfiguration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<S3BucketAclGrantConfiguration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(S3BucketAclGrantConfiguration.class));

       return (TypeAdapter<T>) new TypeAdapter<S3BucketAclGrantConfiguration>() {
           @Override
           public void write(JsonWriter out, S3BucketAclGrantConfiguration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public S3BucketAclGrantConfiguration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of S3BucketAclGrantConfiguration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of S3BucketAclGrantConfiguration
   * @throws IOException if the JSON string is invalid with respect to S3BucketAclGrantConfiguration
   */
  public static S3BucketAclGrantConfiguration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, S3BucketAclGrantConfiguration.class);
  }

  /**
   * Convert an instance of S3BucketAclGrantConfiguration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

