/*
 * Access Analyzer
 * <p>Identity and Access Management Access Analyzer helps identify potential resource-access risks by enabling you to identify any policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview and validate public and cross-account access to your resources before deploying permissions changes. This guide describes the Identity and Access Management Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p> <p>To start using IAM Access Analyzer, you first need to create an analyzer.</p>
 *
 * The version of the OpenAPI document: 2019-11-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Contains details about the CloudTrail trail being analyzed to generate a policy.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:05.234024+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class TrailProperties {
  public static final String SERIALIZED_NAME_CLOUD_TRAIL_ARN = "cloudTrailArn";
  @SerializedName(SERIALIZED_NAME_CLOUD_TRAIL_ARN)
  @javax.annotation.Nonnull
  private String cloudTrailArn;

  public static final String SERIALIZED_NAME_REGIONS = "regions";
  @SerializedName(SERIALIZED_NAME_REGIONS)
  @javax.annotation.Nullable
  private List regions;

  public static final String SERIALIZED_NAME_ALL_REGIONS = "allRegions";
  @SerializedName(SERIALIZED_NAME_ALL_REGIONS)
  @javax.annotation.Nullable
  private Boolean allRegions;

  public TrailProperties() {
  }

  public TrailProperties cloudTrailArn(@javax.annotation.Nonnull String cloudTrailArn) {
    this.cloudTrailArn = cloudTrailArn;
    return this;
  }

  /**
   * Get cloudTrailArn
   * @return cloudTrailArn
   */
  @javax.annotation.Nonnull
  public String getCloudTrailArn() {
    return cloudTrailArn;
  }

  public void setCloudTrailArn(@javax.annotation.Nonnull String cloudTrailArn) {
    this.cloudTrailArn = cloudTrailArn;
  }


  public TrailProperties regions(@javax.annotation.Nullable List regions) {
    this.regions = regions;
    return this;
  }

  /**
   * Get regions
   * @return regions
   */
  @javax.annotation.Nullable
  public List getRegions() {
    return regions;
  }

  public void setRegions(@javax.annotation.Nullable List regions) {
    this.regions = regions;
  }


  public TrailProperties allRegions(@javax.annotation.Nullable Boolean allRegions) {
    this.allRegions = allRegions;
    return this;
  }

  /**
   * Get allRegions
   * @return allRegions
   */
  @javax.annotation.Nullable
  public Boolean getAllRegions() {
    return allRegions;
  }

  public void setAllRegions(@javax.annotation.Nullable Boolean allRegions) {
    this.allRegions = allRegions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrailProperties trailProperties = (TrailProperties) o;
    return Objects.equals(this.cloudTrailArn, trailProperties.cloudTrailArn) &&
        Objects.equals(this.regions, trailProperties.regions) &&
        Objects.equals(this.allRegions, trailProperties.allRegions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cloudTrailArn, regions, allRegions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrailProperties {\n");
    sb.append("    cloudTrailArn: ").append(toIndentedString(cloudTrailArn)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    allRegions: ").append(toIndentedString(allRegions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cloudTrailArn");
    openapiFields.add("regions");
    openapiFields.add("allRegions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("cloudTrailArn");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TrailProperties
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TrailProperties.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TrailProperties is not found in the empty JSON string", TrailProperties.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TrailProperties.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TrailProperties` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TrailProperties.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `cloudTrailArn`
      String.validateJsonElement(jsonObj.get("cloudTrailArn"));
      // validate the optional field `regions`
      if (jsonObj.get("regions") != null && !jsonObj.get("regions").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("regions"));
      }
      // validate the optional field `allRegions`
      if (jsonObj.get("allRegions") != null && !jsonObj.get("allRegions").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("allRegions"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TrailProperties.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TrailProperties' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TrailProperties> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TrailProperties.class));

       return (TypeAdapter<T>) new TypeAdapter<TrailProperties>() {
           @Override
           public void write(JsonWriter out, TrailProperties value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TrailProperties read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TrailProperties given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TrailProperties
   * @throws IOException if the JSON string is invalid with respect to TrailProperties
   */
  public static TrailProperties fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TrailProperties.class);
  }

  /**
   * Convert an instance of TrailProperties to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

